//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by gvk-gen. DO NOT EDIT.

package v1alpha1

const (
	ModelKind  = "Model"
	PromptKind = "Prompt"
)

var (
	ModelGroupVersionKind  = SchemeGroupVersion.WithKind(ModelKind)
	PromptGroupVersionKind = SchemeGroupVersion.WithKind(PromptKind)
)
