run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - durationcheck
    - exportloopref
    - forcetypeassert
    - gocritic
    - makezero
    - nosprintfhostport
    - asciicheck
    - depguard
    - gosec
    - prealloc
    - revive
    - unconvert
    - unparam
    - errcheck
    - govet
    - stylecheck
    - gosimple
    - unused
    - staticcheck
    - gofmt
    - gofumpt
    - gci
    - gocheckcompilerdirectives
    - loggercheck
    - nilerr
    - tenv
    - usestdlibvars
    - forbidigo
    - bodyclose
    - sloglint
    - copyloopvar

linters-settings:
  forbidigo:
    exclude-godoc-examples: true
    forbid:
      - p: .*http\.(Get|Post).*
        msg:
          Do not use Get/Post methods exported by "http" package, they use global http client, which doesnt have proper timeouts. Use http client created for example by github.com/hashicorp/go-cleanhttp.
          It should be created in main func and passed down to any struct that uses it.
      - p: .*http\.DefaultClient.*
        msg:
          Do not use http.DefaultClient, it is a global struct without proper timeouts. Use http client created for example by github.com/hashicorp/go-cleanhttp.
          It should be created in main func and passed down to any struct that uses it.
  usestdlibvars:
    time-month: true
    time-layout: true
    crypto-hash: true
  paralleltest:
    # Ignore missing calls to `t.Parallel()` and only report incorrect uses of it.
    # Default: false
    ignore-missing: true
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(aerf.io/ollama-operator)
      - blank
      - dot
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
      - pattern: "a[b:len(a)]"
        replacement: "a[b:]"
  gofumpt:
    module-path: aerf.io/ollama-operator
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: true
  depguard:
    rules:
      no-sync-atomic:
        deny:
          - pkg: "sync/atomic"
            desc: "please use type-safe atomics from go.uber.org/atomic"
      no-old-yaml-pkg:
        deny:
          - pkg: "gopkg.in/yaml.v2"
            desc: "please use gopkg.in/yaml.v3, not v2"
      only-std-errors-pkg:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib "errors" package or "fmt.Errorf" or "go.uber.org/multierr" package
          - pkg: "github.com/go-errors/errors"
            desc: Should be replaced by standard lib "errors" package or "fmt.Errorf" or "go.uber.org/multierr" package
          - pkg: "golang.org/x/xerrors"
            desc: Should be replaced by standard lib "errors" package or "fmt.Errorf" or "go.uber.org/multierr" package
      only-log-slog:
        deny:
          - pkg: golang.org/x/exp/slog
            desc: please use "log/slog" instead
          - pkg: github.com/sagikazarmark/slog-shim
            desc: please use "log/slog" instead
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - opinionated
      - style
      - experimental
    disabled-checks:
      - rangeValCopy
      - unnamedResult
      - hugeParam
      - paramTypeCombine # automatically fixed by gofumpt
      - typeDefFirst
  gosec:
    excludes:
      - G108 # Profiling endpoint automatically exposed on /debug/pprof - https://github.com/securego/gosec#available-rules
      - G601 # Implicit memory aliasing of items from a range statement - no longer valid because they changed loop var semantics in go1.22
      - G204 # Subprocess launched with a potential tainted input or cmd arguments - https://github.com/securego/gosec/issues/292#issuecomment-480089941
  revive:
    rules:
      - name: indent-error-flow
        disabled: true
issues:
  exclude-use-default: true
  exclude-files:
    - "zz_generated\\..+\\.go$"
  exclude-rules:
    - linters:
        - revive
      text: "blank-imports"
    - path: _test\.go
      linters:
        - forbidigo
      text: "http"
    - path: _test\.go
      linters:
        # failed type asserts are fine in tests because it's development and Go's test harness catches panics, which are risen where the type asssertion fails
        - forcetypeassert
        - goconst
        - gosec
