statefulSet:
  jsonPatch:
    - op: "add"
      path: "/metadata/labels/patched"
      value: "patched-value"
    - op: "replace"
      path: "/spec/volumeClaimTemplates/0/spec/resources/requests/storage"
      value: "30Gi"
    - op: "add"
      path: "/spec/template/spec/containers/1"
      value: {"name": "test", "image": "test:latest"}
  mergePatch:
    metadata:
      annotations:
        test1: test2
    spec:
      replicas: 3
#      someField: 123
#      template:
#        spec:
#          containers:
#            - name: ollama
#              resources:
#                limits:
#                  cpu: 50
#                  memory: 50Gi
