//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by gvk-gen. DO NOT EDIT.

package v1alpha1

const (
	ModelKind               = "Model"
	ProviderConfigKind      = "ProviderConfig"
	ProviderConfigUsageKind = "ProviderConfigUsage"
)

var (
	ModelGroupVersionKind               = SchemeGroupVersion.WithKind(ModelKind)
	ProviderConfigGroupVersionKind      = SchemeGroupVersion.WithKind(ProviderConfigKind)
	ProviderConfigUsageGroupVersionKind = SchemeGroupVersion.WithKind(ProviderConfigUsageKind)
)
