apiVersion: ollama.aerf.io/v1alpha1
kind: Model
metadata:
  labels:
    app.kubernetes.io/name: ollama-operator
    app.kubernetes.io/managed-by: kustomize
  name: model-sample
spec:
  model: phi3
  # TODO(user): Add fields here
