apiVersion: ollama.aerf.io/v1alpha1
kind: Model
metadata:
  name: gemma2-2b
spec:
  model: gemma2:2b
  statefulSetPatches:
    mergePatch:
      spec:
        revisionHistoryLimit: 1
    strategicMergePatch:
      spec:
        template:
          spec:
            containers:
              - name: ollama
                livenessProbe:
                  failureThreshold: 5
