apiVersion: ollama.aerf.io/v1alpha1
kind: Model
metadata:
  name: gemma2-2b
spec:
  recreateOnImmutableError: true
  model: gemma2:2b
  statefulSetPatches:
    mergePatch:
      spec:
        revisionHistoryLimit: 2
