// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ModelRefApplyConfiguration represents a declarative configuration of the ModelRef type for use
// with apply.
type ModelRefApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// ModelRefApplyConfiguration constructs a declarative configuration of the ModelRef type for use with
// apply.
func ModelRef() *ModelRefApplyConfiguration {
	return &ModelRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModelRefApplyConfiguration) WithName(value string) *ModelRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ModelRefApplyConfiguration) WithNamespace(value string) *ModelRefApplyConfiguration {
	b.Namespace = &value
	return b
}
