// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// OllamaModelDetailsApplyConfiguration represents a declarative configuration of the OllamaModelDetails type for use
// with apply.
type OllamaModelDetailsApplyConfiguration struct {
	ParameterSize     *string  `json:"parameterSize,omitempty"`
	QuantizationLevel *string  `json:"quantizationLevel,omitempty"`
	ParentModel       *string  `json:"parentModel,omitempty"`
	Format            *string  `json:"format,omitempty"`
	Family            *string  `json:"family,omitempty"`
	Families          []string `json:"families,omitempty"`
}

// OllamaModelDetailsApplyConfiguration constructs a declarative configuration of the OllamaModelDetails type for use with
// apply.
func OllamaModelDetails() *OllamaModelDetailsApplyConfiguration {
	return &OllamaModelDetailsApplyConfiguration{}
}

// WithParameterSize sets the ParameterSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParameterSize field is set to the value of the last call.
func (b *OllamaModelDetailsApplyConfiguration) WithParameterSize(value string) *OllamaModelDetailsApplyConfiguration {
	b.ParameterSize = &value
	return b
}

// WithQuantizationLevel sets the QuantizationLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QuantizationLevel field is set to the value of the last call.
func (b *OllamaModelDetailsApplyConfiguration) WithQuantizationLevel(value string) *OllamaModelDetailsApplyConfiguration {
	b.QuantizationLevel = &value
	return b
}

// WithParentModel sets the ParentModel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParentModel field is set to the value of the last call.
func (b *OllamaModelDetailsApplyConfiguration) WithParentModel(value string) *OllamaModelDetailsApplyConfiguration {
	b.ParentModel = &value
	return b
}

// WithFormat sets the Format field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Format field is set to the value of the last call.
func (b *OllamaModelDetailsApplyConfiguration) WithFormat(value string) *OllamaModelDetailsApplyConfiguration {
	b.Format = &value
	return b
}

// WithFamily sets the Family field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Family field is set to the value of the last call.
func (b *OllamaModelDetailsApplyConfiguration) WithFamily(value string) *OllamaModelDetailsApplyConfiguration {
	b.Family = &value
	return b
}

// WithFamilies adds the given value to the Families field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Families field.
func (b *OllamaModelDetailsApplyConfiguration) WithFamilies(values ...string) *OllamaModelDetailsApplyConfiguration {
	for i := range values {
		b.Families = append(b.Families, values[i])
	}
	return b
}
