// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

// PatchesApplyConfiguration represents a declarative configuration of the Patches type for use
// with apply.
type PatchesApplyConfiguration struct {
	JSONPatchApplyConfiguration  `json:""`
	MergePatchApplyConfiguration `json:""`
}

// PatchesApplyConfiguration constructs a declarative configuration of the Patches type for use with
// apply.
func Patches() *PatchesApplyConfiguration {
	return &PatchesApplyConfiguration{}
}
