// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PromptResponseMetaApplyConfiguration represents a declarative configuration of the PromptResponseMeta type for use
// with apply.
type PromptResponseMetaApplyConfiguration struct {
	CreatedAt *v1.Time `json:"createdAt,omitempty"`
}

// PromptResponseMetaApplyConfiguration constructs a declarative configuration of the PromptResponseMeta type for use with
// apply.
func PromptResponseMeta() *PromptResponseMetaApplyConfiguration {
	return &PromptResponseMetaApplyConfiguration{}
}

// WithCreatedAt sets the CreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreatedAt field is set to the value of the last call.
func (b *PromptResponseMetaApplyConfiguration) WithCreatedAt(value v1.Time) *PromptResponseMetaApplyConfiguration {
	b.CreatedAt = &value
	return b
}
