// Code generated by controller-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v6/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.crossplane.crossplane-runtime.apis.common.v1.Condition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        namedType: com.github.crossplane.crossplane-runtime.apis.common.v1.ConditionReason
    - name: status
      type:
        namedType: io.k8s.api.core.v1.ConditionStatus
    - name: type
      type:
        namedType: com.github.crossplane.crossplane-runtime.apis.common.v1.ConditionType
- name: com.github.crossplane.crossplane-runtime.apis.common.v1.ConditionReason
  scalar: string
- name: com.github.crossplane.crossplane-runtime.apis.common.v1.ConditionType
  scalar: string
- name: com.github.crossplane.crossplane-runtime.apis.common.v1.SecretKeySelector
  map:
    fields:
    - name: key
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.ConfigMapKeySelector
  map:
    fields:
    - name: key
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.ImageData
  map:
    fields:
    - name: data
      type:
        scalar: string
    - name: format
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.ImageFormat
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.ImageFormat
  scalar: string
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.ImageSource
  map:
    fields:
    - name: configMapKeyRef
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.ConfigMapKeySelector
    - name: inline
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.ImageData
    - name: secretKeyRef
      type:
        namedType: com.github.crossplane.crossplane-runtime.apis.common.v1.SecretKeySelector
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.JSONPatchOperation
  map:
    fields:
    - name: from
      type:
        scalar: string
    - name: op
      type:
        scalar: string
    - name: path
      type:
        scalar: string
    - name: value
      type:
        namedType: __untyped_atomic_
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.Model
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.ModelSpec
    - name: status
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.ModelStatus
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.ModelRef
  map:
    fields:
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.ModelSpec
  map:
    fields:
    - name: model
      type:
        scalar: string
    - name: ollamaImage
      type:
        scalar: string
    - name: recreateOnImmutableError
      type:
        scalar: boolean
    - name: servicePatches
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.Patches
    - name: statefulSetPatches
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.Patches
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.ModelStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: com.github.crossplane.crossplane-runtime.apis.common.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: modelDetails
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.OllamaModelDetails
    - name: observedGeneration
      type:
        scalar: numeric
    - name: ollamaImage
      type:
        scalar: string
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.OllamaModelDetails
  map:
    fields:
    - name: families
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: family
      type:
        scalar: string
    - name: format
      type:
        scalar: string
    - name: parameterSize
      type:
        scalar: string
    - name: parentModel
      type:
        scalar: string
    - name: quantizationLevel
      type:
        scalar: string
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.Patches
  map:
    fields:
    - name: jsonPatch
      type:
        list:
          elementType:
            namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.JSONPatchOperation
          elementRelationship: atomic
    - name: mergePatch
      type:
        namedType: __untyped_atomic_
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.Prompt
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.PromptSpec
    - name: status
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.PromptStatus
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.PromptResponseMeta
  map:
    fields:
    - name: createdAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.PromptResponseMetrics
  map:
    fields:
    - name: evalCount
      type:
        scalar: numeric
    - name: evalDuration
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
    - name: evalRate
      type:
        scalar: string
    - name: loadDuration
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
    - name: promptEvalCount
      type:
        scalar: numeric
    - name: promptEvalDuration
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
    - name: promptEvalRate
      type:
        scalar: string
    - name: totalDuration
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.PromptSpec
  map:
    fields:
    - name: context
      type:
        scalar: string
    - name: images
      type:
        list:
          elementType:
            namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.ImageSource
          elementRelationship: atomic
    - name: modelRef
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.ModelRef
    - name: options
      type:
        namedType: __untyped_atomic_
    - name: prompt
      type:
        scalar: string
    - name: suffix
      type:
        scalar: string
    - name: system
      type:
        scalar: string
    - name: template
      type:
        scalar: string
- name: io.aerf.ollama-operator.apis.ollama.v1alpha1.PromptStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: com.github.crossplane.crossplane-runtime.apis.common.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: context
      type:
        scalar: string
    - name: meta
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.PromptResponseMeta
    - name: metrics
      type:
        namedType: io.aerf.ollama-operator.apis.ollama.v1alpha1.PromptResponseMetrics
    - name: observedGeneration
      type:
        scalar: numeric
    - name: response
      type:
        scalar: string
- name: io.k8s.api.core.v1.ConditionStatus
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: io.k8s.apimachinery.pkg.runtime.RawExtension
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.types.UID
  scalar: string
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
