apiVersion: ollama.aerf.io/v1alpha1
kind: Model
metadata:
  name: gemma2-2b
spec:
  model: gemma2:2b
  statefulSetPatches:
    strategicMergePatch:
      metadata:
        annotations:
          test1: test2
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: ollama
                resources:
                  limits:
                    cpu: 50
                    memory: 50Gi
                env:
                  - name: whatever
                    value: added
  servicePatches:
    strategicMergePatch:
      metadata:
        annotations:
          todo: yeeeeaaaahhh
