apiVersion: ollama.aerf.io/v1alpha1
kind: Model
metadata:
  name: smollm-135m
status:
  (conditions[?type == 'Ready']):
    - status: "True"
  (conditions[?type == 'Synced']):
    - status: "True"
---
apiVersion: v1
kind: Event
reason: RecreatingDueToImmutableField
source:
  component: model-controller
involvedObject:
  apiVersion: v1
  kind: Model
  name: smollm-135m
