# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: patch-immutable-fields
spec:
  steps:
    - name: 00-apply-model
      try:
        - apply:
            file: 00-model.yaml
        - assert:
            file: 00-assert.yaml
    - name: 01-patch-statefulset-error
      try:
        - patch:
            file: 01-model-patch.yaml
        - assert:
            timeout: 15s
            file: 01-assert.yaml
    - name: 02-status-creating
      try:
        - assert:
            timeout: 3m # sts will get recreated, might take a while to start over
            file: 02-assert.yaml
    - name: 03-patch-statefulset-error
      try:
        - patch:
            file: 03-model-patch.yaml
        - assert:
            timeout: 5m # sts will get recreated, might take a while to start over
            file: 03-assert.yaml
